### ISSUE TITLE
FireflyMobile unable to connect using Personal Token, Unsure wheter the issue is the app or my 2fa Authelia

### ISSUE THREAD

**Issue by Joeharrison94** [emansih/FireflyMobile#100]
**Firefly III Server Version:**
5.3.0
**Firefly III Mobile Version:**
2.0.7
**Android Version:**  
10
**Device Information:**  
- BRAND: Huawei 
- MODEL: P30 Pro
--------------------------------------

## Expected Behavior
Login Successful
## Current Behavior
Error using personal access token
## Steps to Reproduce
Attempt login

So I am using authelia on my domain and in order to bypass this I need to provide it with a valid API key to validate in the headers to allow it through and successfully connect. 

- "traefik.http.routers.fireflyiii-rtr-bypass.rule=Headers(`X-Api-Key`, `$FIREFLY_API_KEY`) || Query(`apikey`, `$FIREFLY_API_KEY`)"

In this instance I am using the Personal token value as the X-Api-Key but when I try this I am getting this error in the app:

"Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $"

**Comment by emansih** [comment]
i have been wanting to setup authelia. I will look into it and add support

**Comment by Joeharrison94** [comment]
awesome keep me posted :)

**Comment by emansih** [comment]
After looking at authelia and keycloak, I'm not sure how to implement it from the perspective of Firefly III. authelia and keycloak are used for applications where there is no authentication mechanism but Firefly III has them.

**Comment by emansih** [comment]
well... I could allow users to pass a string to use as a custom header.

**Comment by Joeharrison94** [comment]
That would work usually in Traefik it routes traffic to the authelia container to do the auth before allowing access currently for other containers that have companion apps I tell traefik to check for the X-Api-Key header, and query if it matches the key I specifiy and if it does it bypasses authelia and goes through to the container allowing the app to work without having to authenticate itself as its using the api anyway with the key.

**Comment by emansih** [comment]
are there any android apps that does this? I don't think i can punch through traefik to reach firefly iii without a lot of hack

**Comment by Joeharrison94** [comment]
so you can basically route to firefly iii which will be a https endpoint which youll be able to get to fireflys api as normal e.g. https://firefly.example.com then /api or what ever endpoint it is that it uses, the only thing blocking that is authelia, but as there is no api key currently I can supply that your app uses I cant put a bypass rule into traefik for it, for example I use the nzb360 companion app for sonarr and radarr which uses the https endpoint and the api key in the app, I then create a bypass rule in traefik in my compose file to searach for an api key then check it against my key which I put in an environment variable and if it matches it will skip authelia.

Something like this

```YAML
  fireflyiii:
    image: jc5x/firefly-iii:latest
    container_name: fireflyiii
    volumes:
      - $USERDIR/docker/firefly_iii/export:/var/www/firefly-iii/storage/export
      - $USERDIR/docker/firefly_iii/upload:/var/www/firefly-iii/storage/upload
    env_file: .fireflyiiienv
    ports:
      - "$FIREFLY_PORT:8080"
    depends_on:
      - fireflyiiidb
    networks:
      proxy_net:
        ipv4_address: 10.0.0.22     
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth Bypass
      - "traefik.http.routers.fireflyiii-rtr-bypass.entrypoints=https"
      - "traefik.http.routers.fireflyiii-rtr-bypass.rule=Headers(`X-Api-Key`, `$FIREFLY_API_KEY`) || Query(`apikey`, `$FIREFLY_API_KEY`)"
      - "traefik.http.routers.fireflyiii-rtr-bypass.priority=100"      
      ## HTTP Routers
      - "traefik.http.routers.fireflyiii-rtr.entrypoints=https"
      - "traefik.http.routers.fireflyiii-rtr.rule=Host(`firefly.$DOMAINNAME`)"
      - "traefik.http.routers.fireflyiii-rtr.priority=99"
      ## Middlewares
      - "traefik.http.routers.fireflyiii-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.fireflyiii-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.fireflyiii-rtr.service=fireflyiii-svc"
      - "traefik.http.routers.fireflyiii-rtr-bypass.service=fireflyiii-svc"      
      - "traefik.http.services.fireflyiii-svc.loadbalancer.server.port=8080"  

```
